### ISSUE TITLE
Linux container on windows server 2019

### ISSUE THREAD

**Issue by nikathone** [sixeyed/docker-on-windows#16]
I was wondering if there is a book or more materials where someone could get more information about running linux containers on windows server 2019. Couldn't get more info by reading this book. Thanks in advance for any feedback.

**Comment by sixeyed** [comment]
Not recommended - there are a couple of options but they're not well supported. A mixed cluster (Swarm or Kubernetes) with some Linux and some Windows nodes is better if you have a mixed estate.

I cover this in an episode of my container show on YouTube: https://eltons.show/episodes/ecs-w4/ecs-w4/

**Comment by nikathone** [comment]
@sixeyed thanks for the feedback. Is there a way someone can contact you for training or consultation?
