### ISSUE TITLE
Running docker build on ch03-iis-healthcheck results in build failure at step 6/16

### ISSUE THREAD

**Issue by GrahamDSmith** [sixeyed/docker-on-windows#4]
Output is:

Step 6/16 : RUN msbuild Healthcheck.WebApi.csproj /p:OutputPath=c:\out\Healthcheck         /p:DeployOnBuild=true /p:VSToolsPath=C:\MSBuild.Microsoft.VisualStudio.Web.targets.14.0.0.3\tools\VSToolsPath
 ---> Running in 82394ec8732a
Microsoft (R) Build Engine version 15.1.1012.6693
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 12/16/2017 5:35:27 PM.
Project "C:\src\Healthcheck.WebApi\Healthcheck.WebApi.csproj" on node 1 (default targets).
C:\src\Healthcheck.WebApi\Healthcheck.WebApi.csproj(139,5): error : This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\packages\Microsoft.Net.Compilers.1.0.0\build\Microsoft.Net.Compilers.props.
Done Building Project "C:\src\Healthcheck.WebApi\Healthcheck.WebApi.csproj" (default targets) -- FAILED.

Build FAILED.

I've done some research but not got to the bottom of this yet, however [this StackOverflow question](https://stackoverflow.com/questions/32254439/nuget-packages-are-missing) seems to be related. I can't get the source code to compile locally because of this error but possibly due to not having the right VS2017 components installed. I've run out of time tonight but wanted to get this logged. Cheers!

**Comment by galkzaz** [comment]
same for me

**Comment by ysudhakar** [comment]
Thank you. above steps resolved build issue. added the two missing packages to packages.json.

**Comment by sixeyed** [comment]
Fixed in the [Second Edition](https://www.amazon.com/Docker-Windows-101-production-2nd/dp/1789617375/) :)
