### ISSUE TITLE
Docker-19-03-1.zip does not exist

### ISSUE THREAD

**Issue by nigel-dewar** [sixeyed/docker-on-windows#8]
Hi Elton, just heads up, On fresh windows server 2019, if you do not specify an older version of docker EE, like 18, then the install command here fails

![image](https://user-images.githubusercontent.com/9402456/63648894-ffe9e680-c779-11e9-8c82-77245848d361.png)

And it may be affecting others as well

https://stackoverflow.com/questions/57626342/how-to-install-docker-on-windows-server-2016

I am following your new book. Cheers

**Comment by sixeyed** [comment]
Hey Nigel, I guess this was a temporary issue with the NuGet installer - I've just spun up a new WS2019 machine and it installs 19.03 correctly with the PowerShell commands.
